Components:
      component1:
        name: blurry-faces-onnx
        candidateExecutionLayers: [1,2]
        Containers:
             container1: 
                image: registry.gitlab.polimi.it/ai-sprint/blurry-faces-onnx:tag
                memorySize: 2048
                computingUnits: 0.9
                trustedExecution: False
                networkProtection: False
                fileSystemProtection: False
                GPURequirement: False
                candidateExecutionResources: [RaspPi]
             container2: 
                image: registry.gitlab.polimi.it/ai-sprint/blurry-faces-onnx:tag
                memorySize: 2048
                computingUnits: 0.9
                trustedExecution: False
                networkProtection: False
                fileSystemProtection: False
                GPURequirement: False
                candidateExecutionResources: [VM1]
      component1_partitionX_1:
           name: blurry-faces-onnx_partitionX_1
           candidateExecutionLayers: [1]
           Containers:
             container1: 
                image: registry.gitlab.polimi.it/ai-sprint/blurry-faces-onnx_partitionX_1:tag
                memorySize: 1024
                computingUnits: 0.9
                trustedExecution: False
                networkProtection: False
                fileSystemProtection: False
                GPURequirement: False
                candidateExecutionResources: [RaspPi]
      component1_partitionX_2:
            name: blurry-faces-onnx_partitionX_2
            candidateExecutionLayers: [2]
            Containers:
             container1: 
                image: registry.gitlab.polimi.it/ai-sprint/blurry-faces-onnx_partitionX_2:tag
                memorySize: 1024
                computingUnits: 0.9
                trustedExecution: False
                networkProtection: False
                fileSystemProtection: False
                GPURequirement: False
                candidateExecutionResources: [VM1]
      component2:
        name: mask-detector
        candidateExecutionLayers: [2,3]
        Containers:
             container1:
                image: registry.gitlab.polimi.it/ai-sprint/mask-detector:tag
                memorySize: 4096
                computingUnits: 0.9
                trustedExecution: False
                networkProtection: False
                fileSystemProtection: False
                GPURequirement: False
                candidateExecutionResources: [VM1, VM2, VM3]

